ingress:
  hosts:
    - host: kanban.k8s.com
      paths:
        - path: /api/
          backend:
            serviceName: kanban-app
            servicePort: 8080
        - path: /
          backend:
            serviceName: kanban-ui
            servicePort: 80
  annotations:
    class: nginx