postgres:
  config:
    data:
      - key: POSTGRES_DB
        value: kanban
      - key: POSTGRES_USER
        value: kanban
      - key: POSTGRES_PASSWORD
        value: kanban
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 1000m