repositories:
  - name: stable
    url: https://charts.helm.sh/stable

  - name: ingress-nginx
    url:  https://kubernetes.github.io/ingress-nginx

releases:
  - name: postgres
    namespace: project
    chart: ./charts/postgres
    secrets:
      - ./values/kanban-postgres.yaml

  - name: kanban-app
    namespace: project
    chart: ./charts/app
    values:
      - ./values/kanban-app.yaml

  - name: kanban-ui
    namespace: project
    chart: ./charts/app
    values:
      - ./values/kanban-ui.yaml

  - name: ingress-backend
    namespace: project
    chart: ./charts/ingress
    values:
      - ./values/ingress.yaml

  - name: ingress-controller
    chart: ingress-nginx/ingress-nginx
    namespace: ingress-nginx

  - name: prometheus
    namespace: monitoring
    chart: stable/prometheus
    version: 11.0.4
    secrets:
      - ./values/prometheus.yaml

  - name: prometheus-rules
    namespace: monitoring
    chart: ./charts/prometheus-rules

  - name: grafana
    namespace: monitoring
    chart: ./charts/grafana
    values:
      - ./values/grafana.yaml

