- name: kube-state-metrics.rules
  rules:
  # memory
  - alert: ContainerMemoryUsage
    expr: (sum(container_memory_working_set_bytes{namespace="project"}) BY (instance, name) / sum(container_spec_memory_limit_bytes{namespace="project"} > 0) BY (instance, name) * 100) > 10
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: Container Memory usage (instance {{ $labels.instance }})
      description: Container Memory usage is above 10%\n  VALUE = {{ $value }}\n
