apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-rules.fullname" . }}
  labels:
    {{- include "prometheus-rules.labels" . | nindent 4 }}
data:
  rules.yml: |
    groups:
{{- range $path, $bytes := .Files.Glob .Values.prometheusRulesFiles }}
      # {{ base $path }}
{{ $.Files.Get $path | indent 6 }}
{{- end }}
